; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
  ; --- PANTALLA TOUCH (ILI9341) ---
  adafruit/Adafruit ILI9341 @ ^1.6.0
  adafruit/Adafruit GFX Library @ ^1.11.9
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  
  ; --- GPS ---
  mikalhart/TinyGPSPlus @ ^1.0.3
  
  ; --- MÓDULO SIM ---
  vshymanskyy/TinyGSM @ ^0.11.5

  ; --- SENSOR DE TEMPERATURA/HUMEDAD (AHT10/AHT20) ---
  adafruit/Adafruit AHTX0 @ ^2.0.5